//
//  StringConstantConfigure.h
//  muzzik
//
//  Created by muzzik on 15/4/27.
//  Copyright (c) 2015年 muzziker. All rights reserved.
//

#ifndef muzzik_StringConstantConfigure_h
#define muzzik_StringConstantConfigure_h


#define Image_Emoji                     @"emoImage"
#define Image_At_button                 @"atImage"
#define Image_add_Song                  @"addedsongImage"
#define Image_Add_picture               @"addedpicImage"
#define Image_invisibleImage            @"invisibleImage"
#define Image_visibleImage              @"visibleImage"
#define Image_Next                      @"next"
#define Image_done                      @"done"
#define Image_back                      @"backImage"
#define Image_textwhiteImage            @"textwhiteImage"
#define Image_textblackImage            @"textblackImage"
#define Image_addedpicImage             @"addedpicImage"
#define Image_SwitchingImage            @"SwitchingImage"
#define Image_Textcover                 @"Textcover"
#define Image_Cover                     @"Cover"
#define Image_SuggestUserImage          @"SuggestUserImage"
#define Image_nopictweetImage           @"nopictweetImage"
#define Image_followImageNormal         @"recommendfollow"
#define Image_timeImage                 @"timeImage"
#define Image_retweetImage              @"retweetImage"
#define Image_replyImage                @"replyImage"
#define Image_shareImage                @"shareImage"
#define Image_visibleImage_login        @"loginvisibleImage"
#define Image_invisibleImage_login      @"logininvisibleImage"
#define Image_lineImage                 @"lineImage"
#define Image_yellowretweetImage        @"yellowretweetImage"
#define Image_redretweetImage           @"redretweetImage"
#define Image_blueretweetImage          @"blueretweetImage"
#define Image_searchImage_white         @"searchImage_white"
#define Image_moreImage                 @"moreImage"
#define Image_search_Oranger            @"search3Image"
#define Image_followImageSQ             @"followImageSQ"
#define Image_followedImageSQ           @"followedImageSQ"
#define Image_followedeachotherImageSQ  @"followedeachotherImageSQ"
#define Image_editInformationImage      @"editInformationImage"
#define Image_prifilebgcover            @"prifilebgcover"
#define Image_profilebirthImage         @"profilebirthImage"
#define Image_profileconstellationImage @"profileconstellationImage"
#define Image_profilefansImage          @"profilefansImage"
#define Image_profilefemaleImage        @"profilefemaleImage"
#define Image_profilefollow             @"profilefollow"
#define Image_profilefolloweacherother  @"profilefolloweacherother"
#define Image_profilefollowed           @"profilefollowed"
#define Image_profilefollowerImage      @"profilefollowerImage"
#define Image_profilejobImage           @"profilejobImage"
#define Image_profilelikeImage          @"profilelikeImage"
#define Image_profilemaleImage          @"profilemaleImage"
#define Image_profileschoolImage        @"profileschoolImage"
#define Image_profilesonglistImage      @"profilesonglistImage"
#define Image_profiletopicImage         @"profiletopicImage"
#define Image_profiletweetImage         @"profiletweetImage"
#define Image_settingImage              @"settingImage"
#define Image_addpicImage               @"addpicImage"
#define Image_listImage                 @"listImage"


#define Image_settingavatarscover       @"settingavatarscover"
#define Image_deletesongImage           @"deletesongImage"
#define Image_detailaddedsongImage      @"detailaddedsongImage"
#define Image_detailaddsongImage        @"detailaddsongImage"
#define Image_detaildeleteImage         @"detaildeleteImage"
#define Image_detailfollowedImage       @"detailfollowedImage"
#define Image_detailfollowImage         @"detailfollowImage"
#define Image_sendImage                 @"sendImage"
#define Image_viewprofileImage          @"viewprofileImage"
#define Image_detailretweetImage        @"detailretweetImage"
#define Image_detailreplyImage          @"detailreplyImage"
#define Image_detailshareImage          @"detailshareImage"
#define Image_settingonImage            @"settingonImage"
#define Image_settingoffImage           @"settingoffImage"
#define Image_detailgreyplay            @"detailgreyplay"
#define Image_detailblueplay            @"detailblueplay"
#define Image_detailredplay             @"detailredplay"
#define Image_detailyellowplay          @"detailyellowplay"
#define Image_detailinvisibleImage      @"detailinvisibleImage"
#define Image_detailvisibleImage        @"detailvisibleImage"
#define Image_maleselectedImage         @"maleselectedImage"
#define Image_femaleselectedImage       @"femaleselectedImage"
#define Image_detailstopblueImage       @"detailstopblueImage"
#define Image_detailstoporangeImage     @"detailstoporangeImage"
#define Image_detailstopredImage        @"detailstopredImage"
#define Image_detailstopyellowImage     @"detailstopyellowImage"
#define Image_timelineblueImage         @"timelineblueImage"
#define Image_timelineredImage          @"timelineredImage"
#define Image_timelineyellowImage       @"timelineyellowImage"
#define Image_songlistpostweetImage     @"songlistpostweetImage"
#define Image_recommendarrowImage       @"recommendarrowImage"
#define Image_recommendwhitearrowImage  @"recommendwhitearrowImage"
#define Image_recommendfollow           @"recommendfollow"
#define Image_recommendfollowed         @"recommendfollowed"
#define Image_recommendfollowedeachother    @"recommendfollowedeachother"
#define Image_momentImage               @"momentImage"
#define Image_q_zoneImage               @"q-zoneImage"
#define Image_qqImage                   @"qqImage"
#define Image_sharebgImage              @"sharebgImage"
#define Image_shareclickbgImage         @"shareclickbgImage"
#define Image_wechatImage               @"wechatImage"
#define Image_weiboImage                @"weiboImage"

#define Image_notifollowclickImage      @"notifollowclickImage"
#define Image_notifollowImage           @"notifollowImage"
#define Image_notilikeclickImage        @"notilikeclickImage"
#define Image_notilikeImage             @"notilikeImage"
#define Image_notireplyclickImage       @"notireplyclickImage"
#define Image_notireplyImage            @"notireplyImage"
#define Image_notiretweetclickImage     @"notiretweetclickImage"
#define Image_notiretweetImage          @"notiretweetImage"
#define Image_notitopicclickImage       @"notitopicclickImage"
#define Image_notitopicImage            @"notitopicImage"

#define Image_hottweetbluelikeImage     @"hottweetbluelikeImage"
#define Image_hottweetblueplayImage     @"hottweetblueplayImage"
#define Image_hottweetblueretweetImage  @"hottweetblueretweetImage"
#define Image_hottweetgreylikeImage     @"hottweetgreylikeImage"
#define Image_hottweetgreyreplyImage        @"hottweetgreyreplyImage"
#define Image_hottweetgreyretweetImage      @"hottweetgreyretweetImage"
#define Image_hottweetgreyshareImage        @"hottweetgreyshareImage"
#define Image_hottweetredlikeImage          @"hottweetredlikeImage"
#define Image_hottweetredplayImage          @"hottweetredplayImage"
#define Image_hottweetredretweetImage       @"hottweetredretweetImage"
#define Image_hottweetyellowlikeImage       @"hottweetyellowlikeImage"
#define Image_hottweetyellowplayImage       @"hottweetyellowplayImage"
#define Image_hottweetyellowretweetImage    @"hottweetyellowretweetImage"

#define Image_newbluetopicImage             @"newbluetopicImage"
#define Image_newredtopicImage              @"newredtopicImage"
#define Image_newtopicnumImage              @"newtopicnumImage"
#define Image_newtopictimeImage             @"newtopictimeImage"
#define Image_newyellowtopicImage           @"newyellowtopicImage"
#define Image_topictimeImage                @"topictimeImage"
#define Image_topicsearchImage              @"topicsearchImage"
#define Image_topicriseImage                @"topicriseImage"
#define Image_topicnumImage                 @"topicnumImage"
#define Image_topicholdImage                @"topicholdImage"
#define Image_topicdeclineImage             @"topicdeclineImage"

#define Image_PlayercloseImage              @"PlayercloseImage"
#define Image_PlayerbluecircleplayImage     @"PlayerbluecircleplayImage"
#define Image_PlayerbluecirclestopImage     @"PlayerbluecirclestopImage"
#define Image_PlayerbluelikedImage          @"PlayerbluelikedImage"
#define Image_PlayerbluelikeImage           @"PlayerbluelikeImage"
#define Image_PlayercloseImage              @"PlayercloseImage"
#define Image_PlayercontrolImage            @"PlayercontrolImage"
#define Image_PlayerfollowedeachotherImage  @"PlayerfollowedeachotherImage"
#define Image_PlayerfollowedImage           @"PlayerfollowedImage"
#define Image_PlayerfollowImage             @"PlayerfollowImage"
#define Image_PlayerforwardImage            @"PlayerforwardImage"
#define Image_PlayerlistImage               @"PlayerlistImage"
#define Image_PlayerloopclickImage          @"PlayerloopclickImage"
#define Image_PlayerloopImage               @"PlayerloopImage"
#define Image_PlayernextsongImage           @"PlayernextsongImage"
#define Image_PlayerredcircleplayImage      @"PlayerredcircleplayImage"
#define Image_PlayerredcirclestopImage      @"PlayerredcirclestopImage"
#define Image_PlayerredlikedImage           @"PlayerredlikedImage"
#define Image_PlayerredlikeImage            @"PlayerredlikeImage"
#define Image_PlayerreplyImage              @"PlayerreplyImage"
#define Image_PlayeryellowcircleplayImage   @"PlayeryellowcircleplayImage"
#define Image_PlayeryellowcirclestopImage   @"PlayeryellowcirclestopImage"
#define Image_PlayeryellowlikedImage        @"PlayeryellowlikedImage"
#define Image_PlayeryellowlikeImage         @"PlayeryellowlikeImage"
#define Image_PlayerplayImage               @"PlayerplayImage"
#define Image_PlayershareImage              @"PlayershareImage"
#define Image_PlayerstopImage               @"PlayerstopImage"
#define Image_Notify_clockButton            @"notificationImage"
#define Image_NotifynewnotificationImage    @"newnotificationImage"
#define Image_user_placeHolder              @"User_PlaceHolder"
#define Image_placeholdImage                @"placeholderImage"
#define Image_playerbarcoverImage           @"playerbarcoverImage"
#define Image_cover_CD                      @"cover1080"
#define Image_fontclickImage                @"fontclickImage"
#define Image_fontImage                     @"fontImage"
#define Image_MuzzikImage                   @"MuzzikImage"
#define Image_shareplay                     @"shareplay"
//歌曲播放按钮
#define Image_playblueImage                 @"playblueImage"
#define Image_playgreyImage                 @"playgreyImage"
#define Image_playredImage                  @"playredImage"
#define Image_playyellowImage               @"playyellowImage"
#define Image_songlistbluepostweetImage     @"songlistbluepostweetImage"
#define Image_songlistpostweetImage         @"songlistpostweetImage"
#define Image_songlistredpostweetImage      @"songlistredpostweetImage"
#define Image_songlistyellowpostweetImage   @"songlistyellowpostweetImage"
#define Image_stopblueImage                 @"stopblueImage"
#define Image_stoporangeImage               @"stoporangeImage"
#define Image_stopredImage                  @"stopredImage"
#define Image_stopyellowImage               @"stopyellowImage"

#define Image_userTips                      @"userTips"
#define Image_topicTips                     @"topicTips"
#define Image_musicTips                     @"musicTips"
#define Muzzik_local_Music_Moved_Array      @"Muzzik_local_Music_Moved_Array"



#define Parameter_Id                @"_id"
#define Parameter_avatar            @"avatar"
#define Parameter_Gender            @"gender"
#define Parameter_name              @"name"
#define Parameter_message           @"message"
#define Parameter_image_key         @"image"
#define Parameter_private           @"private"
#define Parameter_reply_id          @"reply"
#define Parameter_repost_id         @"repost"

#define Constant_Data_Square            @"Persistence_suqare_data"
//#define Constant_Data_ownMuzzik         @"Persistence_ownMuzzik_data"
#define Constant_Data_Suggest           @"Persistence_Suggest_data"
#define Constant_Data_topic             @"Persistence_user_topic"
#define Constant_Data_User_Vip          @"Persistence_user_vip"
#define Notification_Number_Dictionary  @"Notification_Number_Dictionary"



#define Notification_comment            1
#define Notification_at                 2
#define Notification_follow             3
#define Notification_moved              4
#define Notification_repost             5
#define Notification_participation      6

#define Constant_Comment            @"Coment"
#define Constant_showComment        @"showComment"
#endif
